### ISSUE TITLE
[GAME BUG]: DOA5LR CRASH

### ISSUE THREAD

**Issue by palmeras** [diegolix29/shadPS4#76]
### Checklist (we expect you to perform these steps before opening the issue)

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.
- [x] I have re-dumped the game and performed a clean install without mods and the issue is still present.
- [x] I have disabled all patches and cheats and the issue is still present.
- [x] I have all the required [system modules](https://github.com/shadps4-emu/shadPS4/wiki/I.-Quick-start-%5BUsers%5D#4-adding-modules) installed.

### Describe the Bug

Dead or Alive 5 Last Round (CUSA01778) and (CUSA01627), crashes and closes after the "ninja_vi.mp4" intro, just when the 3D environment of the stages and the game's menus and options should be displayed. The last build that worked without this error was version 985da0c (2025-07-15), and since then, no build has worked with this game.

### Reproduction Steps

I would appreciate it if you could investigate this error, as it's one of my favorite games, and I'm sad that it stopped working with the most recent updates. The steps are very simple... The game starts and loads fine until it reaches the game menu screen, where it crashes. The configuration used is irrelevant, as the resulting behavior is the same in any configuration..

### Specify OS Version

Windows 11

### CPU

intel core i9-12900KF

### GPU

nvidia RTX4090

### Amount of RAM in GB

64GB

### Amount of VRAM in GB

24GB

### Log File

[shad_log.txt](https://github.com/user-attachments/files/21333266/shad_log.txt)

**Comment by palmeras** [comment]
In the latest build, (cc88d70), DOA5LR works fine again, except for the missing BGM audio, missing fighter voices, and missing particle effects. I trust these issues will be fixed in the near future. THANK YOU.

**Comment by diegolix29** [comment]
can u test on the lastest? i just tried it and i have sound of the character when playing

<img width="1269" height="733" alt="Image" src="https://github.com/user-attachments/assets/cccea93b-8677-480a-b4e6-f671b76e2c55" />

**Comment by diegolix29** [comment]
for the particles try using the dma and both readbacks normal and linear

**Comment by diegolix29** [comment]
i can confirm on the bgm the voices arent there but on the fight they are

and also enabling the dma and linear and normal readbacks make particles show

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/3651b86a-2adb-44f4-bffa-662b66bb6828" />

**Comment by diegolix29** [comment]
im gonna close the issue as is fixed atm but u can make another on re open this if it start craashing againn

**Comment by palmeras** [comment]
Hello, thank you very much for your attention.
I wanted to let you know that the particle activation still isn't working correctly despite your instructions for activating them...let me explain.
The game itself does display "some" particles in the Shadps4 emulator, but not all of them. The explosion effects when a fighter crashes into the electrified fences at the limits of some stages, for example, are very minimal, so the particle effects and "sparkling sparks" are barely visible, if not nonexistent... as well as particle effects from explosions in the "Fireworks" stage, where the explosion of the pyrotechnic rockets in the air does not display the sparkling particles typical of that effect, and only a small "mist" is visible that disappears after the explosion. The game in SHAD PS4 looks practically at the level of the PS3 version as far as these types of missing effects are concerned. To see what I mean, check out this comparison between the PS3 and PS4 versions on YouTube. https://www.youtube.com/watch?v=jOYfPbfRU-8
